-- users와 spots를 잇는 좋아요 이력 테이블. (user_id, spot_id) 유니크 제약이
-- "이 사용자가 이 스팟을 좋아요했는가"의 유일한 진실 소스이자 동시 요청으로 인한
-- 중복 좋아요를 DB 레벨에서 막는 안전장치다.
-- 로컬은 ddl-auto:update가 자동으로 만들어 주지만, 운영은 ddl-auto:validate라 직접 실행해야 한다.
CREATE TABLE IF NOT EXISTS spot_likes (
    spot_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    spot_id BIGINT NOT NULL REFERENCES spots(spot_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_spot_likes_user_spot UNIQUE (user_id, spot_id)
);
CREATE INDEX IF NOT EXISTS idx_spot_likes_spot_id ON spot_likes(spot_id);
