-- 카카오톡 공유 링크로 공동 코스에 참여시키기 위한 멤버·초대 테이블.
-- OWNER는 courses.user_id로 관리하며, 이 테이블에는 VIEWER/EDITOR 초대 참여자만 저장한다.

CREATE TABLE IF NOT EXISTS course_members (
    course_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('VIEWER', 'EDITOR')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_members_course_user UNIQUE (course_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_course_members_user_id
    ON course_members(user_id);

CREATE TABLE IF NOT EXISTS course_invites (
    course_invite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
    created_by_user_id BIGINT NOT NULL REFERENCES users(user_id),
    token VARCHAR(64) NOT NULL UNIQUE,
    member_role VARCHAR(20) NOT NULL CHECK (member_role IN ('VIEWER', 'EDITOR')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_course_invites_course_id
    ON course_invites(course_id);
