-- 기존 GCP 환경 보정용 댓글 마이그레이션.
-- 2026-08-27-create-board-tables.sql에는 comments 정의가 포함돼 있지만,
-- 이미 boards 계열 테이블이 존재하던 GCP DB에는 comments만 누락돼 있었다.
-- 새 환경에서는 기존 board 마이그레이션이 먼저 comments를 만들므로 이 파일은 no-op이다.

-- 댓글·대댓글 저장. 작성자·게시글·부모 댓글의 외래 키로 참조 무결성을 유지한다.
CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    content VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_comments_board FOREIGN KEY (board_id) REFERENCES boards(board_id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments(comment_id)
);

-- 게시글별 활성 댓글 목록 조회에 사용하는 인덱스.
CREATE INDEX IF NOT EXISTS idx_comments_board_status
    ON comments(board_id, status);

-- 부모 댓글을 기준으로 대댓글을 조회할 때 사용하는 인덱스.
CREATE INDEX IF NOT EXISTS idx_comments_parent_comment_id
    ON comments(parent_comment_id);
