-- 게시판 기본 테이블.
-- 게시물은 작성자와 연결되고, 사용자의 코스를 선택적으로 첨부할 수 있다.
CREATE TABLE IF NOT EXISTS boards (
    board_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    user_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    thumbnail VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_boards_course FOREIGN KEY (course_id) REFERENCES courses(course_id),
    CONSTRAINT fk_boards_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS idx_boards_user_status
    ON boards(user_id, status);

CREATE INDEX IF NOT EXISTS idx_boards_course_id
    ON boards(course_id);

-- 게시물 본문에 포함되는 이미지 목록.
CREATE TABLE IF NOT EXISTS board_images (
    board_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(255),
    sequence INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_board_images_board FOREIGN KEY (board_id) REFERENCES boards(board_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_board_images_board_sequence
    ON board_images(board_id, sequence);

CREATE INDEX IF NOT EXISTS idx_board_images_board_id
    ON board_images(board_id);

-- 게시물 좋아요 이력.
CREATE TABLE IF NOT EXISTS board_likes (
    board_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_board_likes_board FOREIGN KEY (board_id) REFERENCES boards(board_id),
    CONSTRAINT fk_board_likes_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_board_likes_user_board
    ON board_likes(user_id, board_id);

CREATE INDEX IF NOT EXISTS idx_board_likes_board_id
    ON board_likes(board_id);

-- 게시물 댓글과 대댓글.
CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    content VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_comments_board FOREIGN KEY (board_id) REFERENCES boards(board_id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments(comment_id)
);

CREATE INDEX IF NOT EXISTS idx_comments_board_status
    ON comments(board_id, status);

CREATE INDEX IF NOT EXISTS idx_comments_parent_comment_id
    ON comments(parent_comment_id);
