-- 코스 기본 테이블.
-- 한 명의 사용자는 여러 코스를 만들 수 있고, 코스는 여러 spot을 순서대로 담는다.
CREATE TABLE IF NOT EXISTS courses (
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    thumbnail VARCHAR(500),
    visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_courses_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS idx_courses_user_status
    ON courses(user_id, status);

-- 코스에 포함된 spot 목록.
-- sequence는 코스 안에서의 정렬 순서이고, 같은 코스에 같은 spot이 중복으로 들어가지 않도록 막는다.
CREATE TABLE IF NOT EXISTS course_spots (
    course_spot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    spot_id BIGINT NOT NULL,
    sequence INT NOT NULL,
    memo VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_course_spots_course FOREIGN KEY (course_id) REFERENCES courses(course_id),
    CONSTRAINT fk_course_spots_spot FOREIGN KEY (spot_id) REFERENCES spots(spot_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_course_spots_course_sequence
    ON course_spots(course_id, sequence);

CREATE UNIQUE INDEX IF NOT EXISTS uk_course_spots_course_spot
    ON course_spots(course_id, spot_id);

CREATE INDEX IF NOT EXISTS idx_course_spots_course_id
    ON course_spots(course_id);

CREATE INDEX IF NOT EXISTS idx_course_spots_spot_id
    ON course_spots(spot_id);

-- 코스 좋아요 이력.
CREATE TABLE IF NOT EXISTS course_likes (
    course_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_course_likes_course FOREIGN KEY (course_id) REFERENCES courses(course_id),
    CONSTRAINT fk_course_likes_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_course_likes_user_course
    ON course_likes(user_id, course_id);

CREATE INDEX IF NOT EXISTS idx_course_likes_course_id
    ON course_likes(course_id);
